version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  ci:
    jobs:
      - test
      - build
jobs:
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm i -g pnpm
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm test
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm i -g pnpm
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build