name: CI

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14.x, 16.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Test
        run: nr test
  # build:
  #     name: Build and Test
  #     timeout-minutes: 15
  #     runs-on: ${{ matrix.os }}
  #     # To use Remote Caching, uncomment the next lines and follow the steps below.
  #     # env:
  #     #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  #     #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  #     strategy:
  #       matrix:
  #         os: [ubuntu-latest]

  #     steps:
  #       - name: Check out code
  #         uses: actions/checkout@v2
  #         with:
  #           fetch-depth: 2

  #       - uses: pnpm/action-setup@v2.0.1
  #         with:
  #           version: 6.32.2

  #       - name: Setup Node.js environment
  #         uses: actions/setup-node@v2
  #         with:
  #           node-version: 16
  #           cache: 'pnpm'

  #       - name: Install dependencies
  #         run: pnpm install

  #       - name: Build
  #         run: pnpm build

  #       - name: Test
  #         run: pnpm test